# Generated by Django 5.1.7 on 2025-03-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
