# Generated by Django 5.1.7 on 2025-03-14 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_course_id'),
        ('trainee_app', '0002_alter_trainee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='course_app.course'),
        ),
    ]
