# Generated by Django 5.1.6 on 2025-03-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0003_trainee_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainee_photos/'),
        ),
    ]
