# Generated by Django 5.1.6 on 2025-03-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0004_trainee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='photo',
        ),
    ]
