# Generated by Django 5.1.6 on 2025-03-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0005_remove_trainee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainee_images/'),
        ),
    ]
